#!/usr/bin/env bash
# Regenerate design/sample-*.html.
#
# The samples are REAL docs-render output on the fictional 'orderhub' fixture,
# with cross-page links rewritten to sample-*.html so the three files browse as a
# set from the design/ directory. NEVER hand-edit them — change the renderer or
# the fixture and re-run this script.
#
# Output is byte-stable: the fixture commit uses fixed identity + dates, and
# DOCS_KIT_NOW pins the generation timestamp. Re-running with no source change
# produces no diff.
#
# Portability floor: bash 3.2, BSD sed, python 3.9.
set -eu

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/.." && pwd)"
work="$(mktemp -d "${TMPDIR:-/tmp}/docs-kit-samples.XXXXXX")"
trap 'rm -rf "$work"' EXIT

fixture="$work/orderhub"
mkdir -p "$fixture"
python3 "$here/fixture/make-fixture.py" "$fixture" >/dev/null

# A fixed commit, so the rendered git ref — and therefore the samples — stay stable.
GIT_AUTHOR_NAME=docs-kit;      GIT_AUTHOR_EMAIL=docs-kit@example.invalid
GIT_COMMITTER_NAME=docs-kit;   GIT_COMMITTER_EMAIL=docs-kit@example.invalid
GIT_AUTHOR_DATE="2026-07-31T09:00:00+00:00"
GIT_COMMITTER_DATE="2026-07-31T09:00:00+00:00"
export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
export GIT_AUTHOR_DATE GIT_COMMITTER_DATE

git -C "$fixture" init -q
git -C "$fixture" symbolic-ref HEAD refs/heads/main
git -C "$fixture" add -A
git -C "$fixture" commit -qm "orderhub fixture"

DOCS_KIT_NOW=2026-07-31T09:30:00 python3 "$repo/scripts/docs_render.py" "$fixture" >/dev/null

banner="<!-- SAMPLE — actual docs-render output on the fictional 'orderhub' fixture (links rewritten to sample-*) -->"
for page in index current changes; do
  sed -e "s|<!-- GENERATED by docs-kit docs-render.*-->|$banner|" \
      -e 's|"index\.html|"sample-index.html|g' \
      -e 's|"current\.html|"sample-current.html|g' \
      -e 's|"changes\.html|"sample-changes.html|g' \
      "$fixture/docs/$page.html" > "$repo/design/sample-$page.html"
done

echo "wrote design/sample-{index,current,changes}.html"
